import { Knex } from "knex";

exports.seed = (knex: Knex) => seed(knex);

function seed(knex) {
  const patientData = [
    {
      id: 1,
      name: "John Doe",
      phone: 36223286328,
      address: "123, ABC Street, XYZ City",
      email: "johndoepnt@test.com",
      age: 25,
      occupation: "Student",
      gender: "Male",
      maritialStatus: "Single",
      description: "",
    },
    {
      id: 2,
      name: "Tom Hanks",
      phone: 35237253723,
      address: "Beverly Hills, Calfornia, USA",
      email: "tomhanks@hollywood.com",
      age: 50,
      occupation: "Actor",
      gender: "Male",
      maritialStatus: "Married",
      description: "",
    },
    {
      id: 3,
      name: "Leonardo DeCaprio",
      phone: 6283682632,
      address: "SunnyVille, Calfornia, USA",
      email: "leonardo@hollywood.com",
      age: 45,
      occupation: "Actor",
      gender: "Male",
      maritialStatus: "Married",
      description: "",
    },
    {
      id: 4,
      name: "Angelina Jolie",
      phone: 36283235263,
      address: "Beverly Hills, Calfornia, USA",
      email: "angelina@hollywood.com",
      age: 45,
      occupation: "Actress",
      gender: "Female",
      maritialStatus: "Married",
      description: "",
    },
    {
      id: 5,
      name: "Alexandra Daddario",
      phone: 3837273528,
      address: "Sunnyville, LA, USA",
      email: "alexandra@hollywood.com",
      age: 35,
      occupation: "Actress",
      gender: "Female",
      maritialStatus: "Single",
      description: "",
    },
    {
      id: 6,
      name: "Gordon Ramaswamy",
      phone: 62832863826,
      address: "Tanjur, TamilNadu, INDIA",
      email: "ramaswamy@hollywood.com",
      age: 48,
      occupation: "Chef",
      gender: "Male",
      maritialStatus: "Married",
      description: "",
    },
    {
      id: 7,
      name: "Charlie Puth",
      phone: 362836238628,
      address: "Brackley Street, London, UK",
      email: "charlieputh@musician.com",
      age: 30,
      occupation: "Musician",
      gender: "Male",
      maritialStatus: "Single",
      description: "",
    },
    {
      id: 8,
      name: "Irfaan Khan",
      phone: 362836283,
      address: "Bandra, Mumbai, INDIA",
      email: "irfaankhan@bollywood.com",
      age: 52,
      occupation: "Actor",
      gender: "Male",
      maritialStatus: "Married",
      description: "",
    },
    {
      id: 9,
      name: "Ana De Armes",
      phone: 323623572,
      address: "Eiffel Tower Road, Paris, UK",
      email: "anadearmes@hollywood.com",
      age: 29,
      occupation: "Software Developer",
      gender: "Female",
      maritialStatus: "Single",
      description: "",
    },
    {
      id: 10,
      name: "Ramadev Baba",
      phone: 32362836,
      address: "Sandhuru Road, Haryana, INDIA",
      email: "ramadevbaba@patanjali.com",
      age: 60,
      occupation: "Spiritual Healer",
      gender: "Male",
      maritialStatus: "Single",
      description: "",
    },
    {
      id: 11,
      name: "Sia",
      phone: 362783283,
      address: "Sunnyville, LA, USA",
      email: "sia@musician.com",
      age: 41,
      occupation: "Musician",
      gender: "Female",
      maritialStatus: "Married",
      description: "",
    },
    {
      id: 12,
      name: "David Guetta",
      phone: 372368283685,
      address: "Sunnyville, LA, USA",
      email: "davidguetta@musician.com",
      age: 45,
      occupation: "Musician",
      gender: "Male",
      maritialStatus: "Married",
      description: "",
    },
    {
      id: 13,
      name: "Jack Dorsey",
      phone: 36236283638,
      address: "Villareign, Tornoto, CANADA",
      email: "jack@ceo.com",
      age: 44,
      occupation: "Technology CEO",
      gender: "Male",
      maritialStatus: "Married",
      description: "",
    },
    {
      id: 14,
      name: "Daniel Ricciardo",
      phone: 36236283638,
      address: "Annie ville, Perth, AUSTRALIA",
      email: "danielr@f1.com",
      age: 32,
      occupation: "F1 Driver",
      gender: "Male",
      maritialStatus: "Married",
      description: "",
    },
    {
      id: 15,
      name: "Anne Hathway",
      phone: 36236283638,
      address: "Villareign, Tornoto, CANADA",
      email: "anne@ceo.com",
      age: 32,
      occupation: "Archiect",
      gender: "Female",
      maritialStatus: "Married",
      description: "",
    },
  ];

  return knex("patients")
    .del()
    .then(() => {
      return knex("patients").insert(patientData);
    });
}
