import { Knex } from "knex";

exports.seed = (knex: Knex) => seed(knex);

function seed(knex) {
  const appointmentData = [
    {
      id: 1,
      date: "2020-02-20",
      startTime: "09:00:00",
      endTime: "09:30:00",
      doctorName: "Dr. John Doe",
      patientName: "Ana De Armes",
      status: "New Patient",
    },
    {
      id: 2,
      date: "2020-02-20",
      startTime: "09:30:00",
      endTime: "10:00:00",
      doctorName: "Dr. Rajnikanth",
      patientName: "Tom Hanks",
      status: "In-Treatment",
    },
    {
      id: 3,
      date: "2020-02-20",
      startTime: "10:00:00",
      endTime: "10:30:00",
      doctorName: "Dr. Nikhil",
      patientName: "Jack Dorsey",
      status: "In-Treatment",
    },
    {
      id: 4,
      date: "2020-02-20",
      startTime: "10:30:00",
      endTime: "11:00:00",
      doctorName: "Dr. Suresh",
      patientName: "Steve Jobs",
      status: "In-Treatment",
    },
    {
      id: 5,
      date: "2020-02-20",
      startTime: "11:00:00",
      endTime: "11:30:00",
      doctorName: "Dr. Satheesh",
      patientName: "Bill Gates",
      status: "In-Treatment",
    },
    {
      id: 6,
      date: "2020-02-20",
      startTime: "11:30:00",
      endTime: "12:00:00",
      doctorName: "Dr. Satish",
      patientName: "Mark Zuckerberg",
      status: "In-Treatment",
    },
    {
      id: 7,
      date: "2020-02-20",
      startTime: "12:00:00",
      endTime: "12:30:00",
      doctorName: "Dr. Sumanth",
      patientName: "Jeff Bezos",
      status: "In-Treatment",
    },
    {
      id: 8,
      date: "2020-02-20",
      startTime: "12:30:00",
      endTime: "13:00:00",
      doctorName: "Dr. Shiva Kishore",
      patientName: "Daniel Riccardo",
      status: "In-Treatment",
    },
    {
      id: 9,
      date: "2020-02-20",
      startTime: "13:00:00",
      endTime: "13:30:00",
      doctorName: "Dr. Sumanth",
      patientName: "Angelina Jolie",
      status: "Recovered",
    },
    {
      id: 10,
      date: "2020-02-20",
      startTime: "13:30:00",
      endTime: "14:00:00",
      doctorName: "Dr. Suresh",
      patientName: "Leonardo DiCaprio",
      status: "Recovered",
    },
    {
      id: 11,
      date: "2020-02-20",
      startTime: "14:00:00",
      endTime: "14:30:00",
      doctorName: "Dr. Satheesh",
      patientName: "Brad Pitt",
      status: "Recovered",
    },
    {
      id: 12,
      date: "2020-02-20",
      startTime: "14:30:00",
      endTime: "15:00:00",
      doctorName: "Dr. Suresh",
      patientName: "Tom Cruise",
      status: "Recovered",
    },
    {
      id: 13,
      date: "2020-02-20",
      startTime: "15:00:00",
      endTime: "15:30:00",
      doctorName: "Dr. Sumanth",
      patientName: "Will Smith",
      status: "Recovered",
    },
    {
      id: 14,
      date: "2020-02-20",
      startTime: "15:30:00",
      endTime: "16:00:00",
      doctorName: "Dr. Sumanth",
      patientName: "Charlie Puth",
      status: "Recovered",
    },
    {
      id: 15,
      date: "2020-02-20",
      startTime: "16:00:00",
      endTime: "16:30:00",
      doctorName: "Dr. Sumanth",
      patientName: "Alexandra Daddario",
      status: "In-Treatment",
    },
    {
      id: 16,
      date: "2020-02-21",
      startTime: "09:00:00",
      endTime: "09:30:00",
      doctorName: "Dr. John Doe",
      patientName: "Sia",
      status: "New Patient",
    },
    {
      id: 17,
      date: "2020-02-21",
      startTime: "09:30:00",
      endTime: "10:00:00",
      doctorName: "Dr. Rajnikanth",
      patientName: "Taylor Swift",
      status: "In-Treatment",
    },
    {
      id: 18,
      date: "2020-02-21",
      startTime: "10:00:00",
      endTime: "10:30:00",
      doctorName: "Dr. Nikhil",
      patientName: "Selena Gomez",
      status: "In-Treatment",
    },
    {
      id: 19,
      date: "2020-02-22",
      startTime: "09:00:00",
      endTime: "09:30:00",
      doctorName: "Dr. Rajasekhar",
      patientName: "David Guetta",
      status: "In-Treatment",
    },
    {
      id: 20,
      date: "2020-02-24",
      startTime: "09:00:00",
      endTime: "09:30:00",
      doctorName: "Dr. Nikhil",
      patientName: "Gordon Ramaswamy",
      status: "In-Treatment",
    },
  ];

  return knex("appointments")
    .del()
    .then(() => {
      return knex("appointments").insert(appointmentData);
    });
}
